backend/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # adminstrations urls
    path('admin/', admin.site.urls),

    # api urls
    path('', include('lipila.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('patron/', include(('patron.urls', 'patron'), namespace='patron')),
    path('momo', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('multimedia/', include(('file_manager.urls', 'file_manager'), namespace='file_manager')),
]

file_manager/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('upload/', views.media_upload, name='media_upload'),
    path('edit/<str:filename>', views.media_edit, name='media_edit'),
    path('play/<str:filename>', views.media_play, name='media_play'),
    path('all/<str:m_type>', views.get_media, name='media_all'),
    path('me/<str:m_type>', views.get_user_media, name='user_media_all'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

lipila/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from patron import views as patron_views
from django.conf.urls import handler404


handler404 = views.custom_404_view


urlpatterns = [
    # message
    path('messages/', views.customer_messages_view, name='customer_messages'),
    path('messages/reply/<int:message_id>/', views.reply_to_message_view, name='reply_to_message'),
    # checkout urls
    path('checkout/<int:id>', views.checkout_subscription, name ="checkout_subscription"),
    path('support/<str:payee>/', views.checkout_momo, name ="checkout_momo"),
    path('checkout/visa/', views.create_purchase, name ="create_purchase"),

    # Luso public urls
    path('', views.index, name='index'),
    path('about/luso', views.about, name='about'),
    path('<str:title>/', views.creator_index, name='creator_index'),
    path('contact/lpa/', views.contact, name='contact'),

    # PatronUser defined authenticated user views
    path('dashboard/me/', patron_views.dashboard, name='dashboard'),
    path('dashboard/staff/', views.staff_users, name='staff_dashboard'),
        
    # lipila difened authenticated user views
    path('approve_withdrawals/lpa/', views.approve_withdrawals, name ='approve_withdrawals'),
    path('processed_withdrawals/lpa/', views.processed_withdrawals, name ='processed_withdrawals'),
    path('faq/ls/', views.pages_faq, name='faq'),
    path('terms-of-use/ls/', views.pages_terms, name='terms'),
    path('privacy-policy/ls', views.pages_privacy, name='privacy'),

    path('history/transfers/', views.transfers_history, name='transfers_history'),
    # Authenticated User's Transaction History endpoints
    path('history/withdrawals/', patron_views.withdrawal_history, name='withdrawals_history'),
    path('subscription/history/paid/', patron_views.payments_history, name='subscriptions_history'),
    
    # Modal-forms urls
    path('money/transfer/', views.money_transfer_view, name ='money_transfer'),
    path('withdrawals/request', views.CreateWithdrawalRequest.as_view(), name ='withdrawals'),
    path('update/<int:pk>', views.TierUpdateView.as_view(), name ='update_tier'),
    path('view/<int:pk>', views.TierReadView.as_view(), name ='view_tier'),
    path('delete/<int:pk>', views.TierDeleteView.as_view(), name ='delete_tier'),

    path('unsubscribe/<int:tier_id>', views.UnsubScribeView.as_view(), name='unsubscribe'),
    path('tiers/ls', views.tiers, name = 'tiers'),

    path('approve/<int:pk>', views.ApproveWithdrawModalView.as_view(), name='approve_withdraw'),
    path('reject/<int:pk>', views.RejectWithdrawModalView.as_view(), name='reject_withdraw'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

file_manager/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.validators import FileExtensionValidator
from patron.models import Tier

fs = FileSystemStorage()  # Default storage

class UploadedFile(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="multimedia")
    filename = models.CharField(max_length=255)
    short_reference = models.CharField(max_length=255, blank=True)
    long_reference = models.TextField(max_length=500, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    content_type = models.CharField(max_length=255)
    is_private = models.BooleanField(default=False)
    tiers = models.ManyToManyField(Tier, related_name='multimedia', blank=True)
    file = models.FileField(
        upload_to=fs.path,
        storage=fs,
         validators=[FileExtensionValidator(
             allowed_extensions=['mp3', 'wav', 'mp4', 'avi', 'mov', 'pdf', 'png', 'jpg', 'jpeg'])])

    def __str__(self):
        return self.filename

file_manager/forms.py
from django import forms
from .models import UploadedFile
from patron.models import Tier

class UploadFileForm(forms.Form):
    file = forms.FileField()


class EditMediaFileForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['short_reference',
                  'long_reference', 'is_private', 'tiers']

        labels = {
            'short_reference': 'Title',
            'long_reference': 'reference',
            'is_private': 'Private',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['tiers'].queryset = Tier.objects.filter(creator=user)

file_manager/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import UploadFileForm, EditMediaFileForm
from django.conf import settings
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from .models import UploadedFile
from .utils import get_user_files
from django.db.models import Q


def media_edit(request, filename):
    media_file = get_object_or_404(UploadedFile, filename=filename)

    if request.method == 'POST':
        form = EditMediaFileForm(
            request.POST, request.FILES, instance=media_file, user=request.user.creatorprofile)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated successfully")
            return redirect(reverse('file_manager:media_play', kwargs={'filename': filename}))
    else:
        form = EditMediaFileForm(instance=media_file, user=request.user.creatorprofile)

    fs = FileSystemStorage()
    file_url = fs.url(filename)
    content_type = media_file.content_type
    context = {
        'filename': filename,
        'file_url': file_url,
        'm_type': content_type,
        'form': form
    }

    return render(request, 'file_manager/media_edit.html', context)


def media_delete(request, filename):
    pass


def media_play(request, filename):
    fs = FileSystemStorage()
    file_url = fs.url(filename)
    media_file = get_object_or_404(UploadedFile, filename=filename)

    content_type = media_file.content_type
    reference = media_file.long_reference
    title = media_file.short_reference
    upload_date = media_file.upload_date
    owner = media_file.owner

    context = {'file_url': file_url,
               'owner': owner,
               'filename': filename,
               'short_reference': title,
               'm_type': content_type,
               'long_reference': reference,
               'upload_date': upload_date}
    return render(request, 'file_manager/media_play.html', context)


def media_upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            fs = FileSystemStorage()
            filename = fs.save(file.name, file)
            media_file = UploadedFile.objects.create(
                owner=request.user,
                filename=filename,
                content_type=file.content_type,
            )
            # Get the full path using fs.path(filename)
            file_path = fs.path(filename)
            media_file.file = file_path  # Save the full path to the file field
            media_file.save()
            messages.success(request, "File uploaded")
            return redirect(reverse("file_manager:media_edit", kwargs={'filename': filename}))
    else:
        form = UploadFileForm()
        return render(request, 'file_manager/media_upload.html', {'form': form})


@login_required
@user_passes_test(lambda u: u.is_staff)
def get_media(request, m_type):
    """
    Gets all media files on the system

    Args:
        request: The incoming HTTP request
        m_type(str): The type of media to retrieve. Options are (Video, Audio)

    Returns:
        Renders HTML template showing all video/audio files.
    """
    context = {'m_type': m_type}
    media = []

    try:
        if m_type == 'Video':
            media = get_list_or_404(UploadedFile, content_type='video/mp4')
        elif m_type == 'Audio':
            media = get_list_or_404(UploadedFile, content_type='audio/mpeg')
    except Http404:
        return render(request, 'file_manager/media_all.html', context)

    context['media'] = media
    return render(request, 'file_manager/media_all.html', context)


@login_required
@user_passes_test(lambda u: u.is_creator)
def get_user_media(request, m_type):
    context = {'m_type': m_type}
    if m_type == 'Video':
        files = get_user_files(request.user, 'video/mp4')
        context['media'] = files
    elif m_type == 'Audio':
        files = get_user_files(request.user, 'audio/mpeg')
        context['media'] = files
  
    return render(request, 'file_manager/media_all.html', context)

file_manager/templates/file_manager/_media_list.html
{% load custom_filters %}
<div class="media-items-preview">
    <ul class="media-list-preview">
        {% for file in media %}
        <a href="{% url 'file_manager:media_play' file.filename %}" class="btn-sm m-btn">
            <li class="media-item-preview column {{file.content_type | add_class_from_mime}}">
                <div class="media-player-preview">
                    {% if file.content_type == 'video/mp4' %}
                    <video width="40" height="100" controls="">
                        <source src="{{ file.filename | get_file_url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                    {% elif file.content_type == 'audio/mpeg' %}
                    <div id="audio-player" class="media-player-a">
                        <audio controls="controls" preload="preload">
                            <source src="{{ file.filename | get_file_url }}" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </div>
                    {% elif file.content_type == 'application/pdf' %}
                    {{file.filename}}
                    {% elif file.content_type == 'image/png' %}
                    <img src="{{ file.filename | get_file_url }}">
                    {% endif %}

                    <div class="media-texts-preview">
                        <p class="media-f-d-preview">{{file.short_description}}</p>
                    </div>

                    <div class="action-btns-preview">

                    </div>
                </div>
            </li>
        </a>
        {% endfor %}
    </ul>
</div>

file_manager/templates/file_manager/media_all.html
{% extends 'layout_admin.html' %}
{% block title %} Media {% endblock title %}
{% load static %}
{% load custom_filters %}

{% block extrastylesheets %}
<link href="{% static 'file_manager/css/style.css' %}" rel="stylesheet">
{% endblock extrastylesheets %}
{% block section %}
<div class="media-container">
    {% if request.user.creatorprofile %}
    <h1> My Files </h1>
    {% elif request.user.is_staff %}
    <h1>Files</h1>
    {% endif %}
    {% if media %}
    <ul class="media-list">
        {% for file in media %}
        <li class="media-item-preview">
            <div class="media-player-previe">
                {% if file.content_type == 'video/mp4' %}
                <video width="320" height="240" controls="controls">
                    <source src="{{ file.filename | get_file_url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                {% elif file.content_type == 'audio/mpeg' %}
                <audio controls>
                    <source src="{{ file.filename | get_file_url }}" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>
                {% endif %}
                
                <div class="media-texts">
                    <h4 class="owner">{{file.owner}}</h4>
                    <p class="upload-date">{{file.upload_date}}</p>
                    <h2 class="media-f-n">{{file.short_description}}</h2>
                    <p class="media-f-d">{{file.long_description}}</p>
                    <h4>Visible to:</h4>
                    <p>{{file.tiers}}</p>
                </div>
                
                <div class="media-texts">
                    {% if request.user == file.owner  and request.user.creatorprofile %}
                    <a href="{% url 'file_manager:media_edit' filename=file.filename %}" class="edit-btn btn-sm">Settings</a>
                    <a href="{% url 'file_manager:media_upload'%}" class="edit-btn btn-sm">Add media</a>
                    {% elif request.user.is_staff %}
                    <a href="{% url 'file_manager:media_edit' filename=file.filename %}" class="edit-btn btn-sm">Settings</a>
                    <a href="#"> Disable</a>
                    <a href="#"> Delete</a>
                    {% endif %}
                </div>

            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No {{ m_type }} files found.</p>
    {% if request.user.creatorprofile %}
    <a href="{% url 'file_manager:media_upload' %}">Create</a>
    {% endif %}
    {% endif %}
</div>
{% endblock section %}

file_manager/templates/file_manager/media_edit.html
{% extends 'layout_admin.html' %}

{% block title %}Edit{% endblock title%}
{%load static%}

{% block extrastylesheets %}
<link href="{% static 'file_manager/css/style.css' %}" rel="stylesheet">
<!-- Include Select2 CSS -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

<!-- Include Select2 JS -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>

{% endblock extrastylesheets %}
{% block section%}
<div class="media-container">
    <h1>Edit</h1>
    {% if filename %}
    <div class="media-player">
        {% if m_type == 'video/mp4' %}
        <div id="video-player" class="media-player-v">
            <video controls="controls" preload="preload" >
                <source src="{{ file_url }}" type="video/mp4">
                </source>
            </video>
        </div>

        {% elif m_type == 'audio/mpeg' %}
        <div id="audio-player" class="media-player-a">
            <audio controls="controls" preload="preload">
                <source src="{{ file_url }}" type="audio/mpeg">
                </source>
            </audio>
        </div>
        {% endif %}
    </div>
    <div class="media-edit-form">
        <form method="post">
            {% csrf_token %}
            {{ form.short_description.label_tag }} {{ form.short_description }}
            {{ form.long_description.label_tag }} {{ form.long_description }}
            {{ form.is_private.label_tag }} {{ form.is_private }}
            <label for="id_tiers">Tiers</label>
            {{ form.tiers }}
            <button class="edit-btn" type="submit">Save</button>
        </form>
        <a href="#" class="delete-btn">Delete</a>
    </div>
    {% endif %}
</div>
{% endblock section %}

{% block extrascripts %}
<script>
    $(document).ready(function () {
        $('.delete-btn').click(function (e) {
            e.preventDefault();
            if (confirm("Are you sure you want to delete this file?")) {
                // Perform delete action
                alert("File deleted.");
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        $('#id_tiers').select2({
            placeholder: "Select who can this?",
            allowClear: true
        });
    });
</script>
{% endblock extrascripts%}

file_manager/templates/file_manager/media_play.html
{% extends 'layout_admin.html' %}
{% block title %} Play media {% endblock title %}
{% load static %}

{% block extrastylesheets %}
<link href="{% static 'file_manager/css/style.css' %}" rel="stylesheet">
{% endblock extrastylesheets %}
{% block section %}
<div class="media-container">
	{% if file_url %}
	<div class="media-player">
		{% if m_type == 'video/mp4' %}
		<div id="video-player" class="media-player-v">
			<video autoplay="autoplay" controls="controls" preload="preload" muted="true">
				<source src="{{ file_url }}" type="video/mp4">
				</source>
			</video>
		</div>

		{% elif m_type == 'audio/mpeg' %}
		<div id="audio-player" class="media-player-a">
			<audio controls="controls" preload="preload">
				<source src="{{ file_url }}" type="audio/mpeg">
				</source>
			</audio>
		</div>
		{% endif %}
		<div class="media-texts">
			<h4 class="owner">{{owner}}</h4>
			<p class="upload-date">{{upload_date}}</p>
			<h2 class="media-f-n">{{short_description}}</h2>
			<p class="media-f-d">{{long_description}}</p>
		</div>
	</div>
	<div class="action-btns">
		{% if request.user == file.owner %}
		<a href="{% url 'file_manager:media_edit' filename=filename %}" class="edit-btn">Settings</a>
		{% elif request.user.is_staff %}
		<a href="#"> Disable</a>
		<a href="#"> Delete</a>
		{% endif %}
	</div>
	{% endif %}
</div>
{% endblock section %}

file_manager/templates/file_manager/media_upload.html
{% extends 'layout_admin.html' %}

{% block title %}Upload Video{% endblock title%}
{%load static%}

{% block section%}
<div class="media-upload">
	<fieldset name="File Upload">
		{% if msg %} {% autoescape off %} {{ msg }} {% endautoescape %} {% endif %}
		<form method="post" action="{% url 'file_manager:media_upload' %}" enctype="multipart/form-data">
			{% csrf_token %}
			<dl>
				<p>
					<label>Browse and select a file</label>&nbsp;&nbsp;
					<input type="file" name="file" autocomplete="off" required>
				</p>
			</dl>
			<p>
				<input type="submit" value="Upload and Display">
			</p>
		</form>
	</fieldset>
</div>
{%endblock section %}