accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('sign-out', views.custom_logout, name='logout'),
    path('signin/', views.custom_login_view, name="signin"),
    path('sent/', views.activation_sent_view, name="activation_sent"),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    
    #Callback urls
    path('tiktok/callback/', views.tiktok_callback, name='tiktok_callback'),
    path('google/callback/', views.google_callback, name='google_callback'),
    path('tiktok_oauth/', views.tiktok_oauth, name='tiktok_oauth'),
]

backend/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # adminstrations urls
    path('admin/', admin.site.urls),

    # api urls
    path('', include('lipila.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('patron/', include(('patron.urls', 'patron'), namespace='patron')),
    path('momo', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('multimedia/', include(('file_manager.urls', 'file_manager'), namespace='file_manager')),
]

lipila/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from patron import views as patron_views
from django.conf.urls import handler404


handler404 = views.custom_404_view


urlpatterns = [
    # message
    path('messages/', views.customer_messages_view, name='customer_messages'),
    path('messages/reply/<int:message_id>/', views.reply_to_message_view, name='reply_to_message'),
    # checkout urls
    path('checkout/<int:id>', views.checkout_subscription, name ="checkout_subscription"),
    path('support/<str:payee>/', views.checkout_momo, name ="checkout_momo"),
    path('checkout/visa/', views.create_purchase, name ="create_purchase"),

    # Luso public urls
    path('', views.index, name='index'),
    path('about/luso', views.about, name='about'),
    path('<str:title>/', views.creator_index, name='creator_index'),
    path('contact/lpa/', views.contact, name='contact'),

    # PatronUser defined authenticated user views
    path('dashboard/me/', patron_views.dashboard, name='dashboard'),
    path('dashboard/staff/', views.staff_users, name='staff_dashboard'),
        
    # lipila difened authenticated user views
    path('approve_withdrawals/lpa/', views.approve_withdrawals, name ='approve_withdrawals'),
    path('processed_withdrawals/lpa/', views.processed_withdrawals, name ='processed_withdrawals'),
    path('faq/ls/', views.pages_faq, name='faq'),
    path('terms-of-use/ls/', views.pages_terms, name='terms'),
    path('privacy-policy/ls', views.pages_privacy, name='privacy'),

    path('history/transfers/', views.transfers_history, name='transfers_history'),
    # Authenticated User's Transaction History endpoints
    path('history/withdrawals/', patron_views.withdrawal_history, name='withdrawals_history'),
    path('subscription/history/paid/', patron_views.payments_history, name='subscriptions_history'),
    
    # Modal-forms urls
    path('money/transfer/', views.money_transfer_view, name ='money_transfer'),
    path('withdrawals/request', views.CreateWithdrawalRequest.as_view(), name ='withdrawals'),
    path('update/<int:pk>', views.TierUpdateView.as_view(), name ='update_tier'),
    path('view/<int:pk>', views.TierReadView.as_view(), name ='view_tier'),
    path('delete/<int:pk>', views.TierDeleteView.as_view(), name ='delete_tier'),

    path('unsubscribe/<int:tier_id>', views.UnsubScribeView.as_view(), name='unsubscribe'),
    path('tiers/ls', views.tiers, name = 'tiers'),

    path('approve/<int:pk>', views.ApproveWithdrawModalView.as_view(), name='approve_withdraw'),
    path('reject/<int:pk>', views.RejectWithdrawModalView.as_view(), name='reject_withdraw'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

patron/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     path('request-payment/', views.PatronPaymentRequestView.as_view(), name='request-payment'),
     # Public URLS
     path('creators/', views.index, name='index'),

     path('creators/list', views.browse_creators, name='creators'),
     path('my-tiers', views.view_tiers, name='tiers'),
     path('join/<int:tier_id>', views.subscribe_view, name='join_tier'),
     path('patron/all/', views.view_patrons_view, name='patrons'),
     path('subscriptions/', views.subscriptions, name='subscriptions'),
     path('subscription/<int:tier_id>', views.subscription_detail, name='subscription_detail'),
     path('withdraw/', views.withdrawal_request, name='withdraw_request'),

     # Profile views
     # cretaor kyc
     path('accounts/profile/kyc/overview', views.kyc, name='kyc'),
     path('accounts/profile/kyc/<int:pk>', views.kyc_review, name='kyc_review'),
     path('accounts/profile/continue/fans', views.continue_has_fan, name="continue_has_fan"),
     path('accounts/profile/', views.profile, name='profile'),
     path('accounts/profile/edit/<str:user>/patron', views.ProfileEdit.as_view(), name='update_profile'),
     path('accounts/profile/edit/<str:user>', views.EditPersonalInfo.as_view(), name='update_personal_info'),
     path('accounts/profile/create/creator', views.create_creator_profile,
          name='create_creator_profile'),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

lipila-project/accounts/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse

#  custom modules
from .utils import basic_auth_encode, basic_auth_decode
from .forms import SignUpForm

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from google.oauth2 import id_token
from google.auth.transport import requests
from django.conf import settings

import random
import string

TIKTOK_CLIENT_KEY = settings.TIKTOK_CLIENT_KEY
SERVER_ENDPOINT_REDIRECT=settings.SERVER_ENDPOINT_REDIRECT

def oauth(request):
    # Generate a random CSRF token
    csrf_state = ''.join(random.choices(string.ascii_lowercase + string.digits, k=16))

    # Set the CSRF token as a cookie
    response = HttpResponse()
    response.set_cookie('csrfState', csrf_state, max_age=60)

    # Build the TikTok authorization URL
    url = 'https://www.tiktok.com/v2/auth/authorize/'
    url += f'?client_key={TIKTOK_CLIENT_KEY}'
    url += '&scope=user.info.basic'
    url += '&response_type=code'
    url += f'&redirect_uri={SERVER_ENDPOINT_REDIRECT}'
    url += f'&state={csrf_state}'

    # Redirect to the TikTok authorization URL
    return redirect(url)


def sign_in(request):
    return render(request, 'registration/signin.html')


@csrf_exempt
def auth_receiver(request):
    """
    Google calls this URL after the user has signed in with their Google account.
    """
    token = request.POST.get('credential')

    if not token:
        return HttpResponse(status=400)  # Bad request if no token is provided

    try:
        user_data = id_token.verify_oauth2_token(
            token, requests.Request(), settings.GOOGLE_OAUTH_CLIENT_ID)
    except ValueError:
        return HttpResponse(status=403)  # Forbidden if token is invalid

    email = user_data.get('email')

    if not email:
        return HttpResponse(status=400)  # Bad request if no email in token

    # Get or create the user
    user, created = get_user_model().objects.get_or_create(email=email, defaults={
        'username': email.split('@')[0],  # You can modify this as needed
        'first_name': user_data.get('given_name', ''),
        'last_name': user_data.get('family_name', ''),
    })

    if created:
        messages.success(request, "Account created.")
        user.set_unusable_password()  # Set unusable password if creating a new user
        user.save()

    # Authenticate and log in the user
    user = authenticate(request, email=email)
    if user is not None:
        messages.success(request, f"Welcome back, {user.username}!")
        login(request, user)
        request.session['user_data'] = user_data
        return redirect(reverse('dashboard'))
    else:
        messages.error(request, "Authentication failed")
        return redirect(reverse('accounts:signup'))


def sign_out(request):
    del request.session['user_data']
    return redirect('accounts:signin')


def activation_sent_view(request):
    return render(request, 'registration/activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = basic_auth_decode(uidb64)
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        # Default backend or specific one
        backend = settings.AUTHENTICATION_BACKENDS[0]
        login(request, user, backend=backend)
        return redirect('patron:create_creator_profile')
    else:
        return render(request, 'registration/activation_invalid.html')


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Please Activate Your Account'
            uid64 = basic_auth_encode(user.pk)
            token = default_token_generator.make_token(user)
            message = render_to_string('registration/activation_request.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': uid64,
                'token': token,
            })
            user.email_user(subject, message)
            return redirect('accounts:activation_sent')
        else:
            messages.error(request, "Invalid form fields.")
            form = SignUpForm()
            return render(request, 'registration/signup.html', {'form': form})

    form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def custom_login_view(request):
    if request.method == 'POST':
        next_url = request.GET.get('next', 'dashboard')
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if user.has_group or user.is_staff:
                    messages.success(request, f"Welcome back, {user.username}!")
                    return redirect(next_url)
                else:
                    return redirect('patron:create_creator_profile')
            else:
                form = AuthenticationForm()
                return render(request, 'registration/login.html', {'form': form})
        else:
            messages.error(request, "Invalid username or password.")
            form = AuthenticationForm()
            return render(request, 'registration/login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})

lipila-project/templates/admin_layout.html
{% load static %}
{% load custom_filters%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">

    {% block stylesheets %}
    <!-- Favicons -->
    <link href="{% static 'assets/img/logo-color.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.5/dist/quill.bubble.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
    {% endblock stylesheets %}
    {% block extrastylesheets %}{% endblock extrastylesheets %}

    <title>Lipila-{% block title %}{% endblock title %}</title>
</head>

<body>
    {% if request.user.is_authenticated %}
    {% include '_header.html' %}
    {% include '_aside.html' %}
    {% else %}
    {% include '_header_unauth.html' %}
    {% endif %}
    <main id="main" class="main">
        {% if request.user.creatorprofile or request.user.is_staff %}
        <div class="pagetitle">
            <h1>Dashboard</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </nav>
        </div>
        {% endif %}
        <section class="section dashboard">
            {% if messages %}
            <div class="message">
                <span class="close-btn">&times;</span>
                {% for message in messages %}
                <p class="alert alert-{{ message.tag }}">{{message}}</p>
                {% endfor %}
            </div>
            {% endif %}

            {% block section %}
            {% endblock section %}
        </section>
    </main><!-- End #main -->

    {% include '_footer.html' %}

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>
    <!-- Preloader -->
    <div id="preloader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>

    {% block scripts %}
    <!-- Bootstrap 4 -->
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script> -->
    <!-- You can alternatively load the minified version -->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <!-- Vendor JS Files -->
    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
    {% endblock scripts %}

    {% block extrascripts %}{%endblock extrascripts%}
</body>

</html>

lipila-project/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Lipila-{% block title %} {% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/logo-color.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.3.0/css/glightbox.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/nav.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">


    <!-- =======================================================
  * Template Name: Lipila
  * Updated: Feb 01 2024 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/lipila-bootstrap-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page" data-bs-spy="scroll" data-bs-target="#navmenu">

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="container-fluid d-flex align-items-center justify-content-between">

            <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-xl-4">
                <img src="{% static 'assets/img/logo-color.png' %}" alt="">
                <span></span>
            </a>
            <!-- Nav Menu -->
            <nav id="navmenu" class="navmenu">
                <ul>
                    {% if request.user.creatorprofile or request.user.is_staff %}
                    <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                    {% else %}
                    <li><a href="/#hero">Home</a></li>
                    {% endif %}
                    {% with target_fragment='#creators-info' %}
                    <li><a href="{% url 'patron:index' %}?fragment={{ target_fragment }}">Creators</a></li>
                    {% endwith %}
                    {% with target_fragment='#find-creator' %}
                    <li><a href="{% url 'patron:creators' %}?fragment={{ target_fragment }}">Find a Creator</a></li>
                    {% endwith %}
                    <li><a href="/#features">Features</a></li>
                    <li><a href="/#pricing">Pricing</a></li>
                </ul>

                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav><!-- End Nav Menu -->

            <div>
                {% if request.user.is_authenticated %}
                <p>
                <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" id="btn-getstarted" class="btn-getstarted">Logout</button>
                </form>
                </p>
                {% else %}
                <p><a id="btn-getstarted" class="btn-getstarted" href="{% url 'login' %}">Login</a></p>
                {% endif %}
            </div>

        </div>
    </header><!-- End Header -->
    <!-- display any message -->
    {% if messages %}
    <div class="message">
        <span class="close-btn">&times;</span>
        {% for message in messages %}
        <p class="alert alert-{{ message.tag }}">{{message}}</p>
        {% endfor %}
    </div>
    {% endif %}
    <!-- end message -->

    {% block section %}
    {% endblock %}
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="container footer-top">
            <div class="row gy-4">
                <div class="col-lg-5 col-md-12 footer-about">
                    <a href="{% url 'index' %}" class="logo d-flex align-items-center">
                        <span>Lipila Patron</span>
                    </a>
                    <p>Made for Creators by Creators.</p>
                    <div class="social-links d-flex mt-4">
                        <a href=""><i class="bi bi-twitter"></i></a>
                        <a href=""><i class="bi bi-facebook"></i></a>
                        <a href=""><i class="bi bi-instagram"></i></a>
                        <a href=""><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>Quick Links</h4>
                    <ul>
                        {% if request.user.creatorprofile or request.user.is_staff %}
                        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        {% else %}
                        <li><a href="/#hero">Home</a></li>
                        {% endif %}
                        <li><a href="/#about">About us</a></li>
                        <li><a href="/#services">Services</a></li>
                        <li><a href="{% url 'terms' %}">Terms of use</a></li>
                        <li><a href="{% url 'privacy' %}">Privacy policy.</a></li>
                        <li><a href="{% url 'faq' %}">FAQ</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>Creators</h4>
                    <ul>
                        <li><a href="#">Video Creators</a></li>
                        <li><a href="#">Musicians</a></li>
                        <li><a href="#">Podcasters</a></li>
                        <li><a href="#">Artists</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                    <h4>Pricing</h4>
                    <p>FREE!</p>
                </div>

            </div>
        </div>

        <div class="container copyright text-center mt-4">
            <p>&copy; <span>Copyright</span> <strong class="px-1">Lipila Technologies Ltd</strong> <span>All Rights
                    Reserved</span></p>
            <div class="credits">
                Designed by <a href="#">Lipila Technologies Limited</a>
            </div>
        </div>

    </footer><!-- End Footer -->

    <!-- Scroll Top Button -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>

    <!-- Vendor JS Files -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/glightbox/3.3.0/js/glightbox.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@srexi/purecounter.js/dist/purecounter_vanilla.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

lipila-project/templates/dark_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="description">
  <meta content="" name="keywords">
  <title>{% block title %} {% endblock %}</title>
  <link href="{% static 'assets/img/logo-color.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evSXBKlOz+zmr2T7+qmWpIej0zWwmoQhCoqVLxHfhgjQvBPIaOUtWznreUT2ONu" crossorigin="anonymous">
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
</head>

<body>
  {% if messages %}
  <div class="message">
    {% for message in messages %}
    <p class="alert alert-{{ message.tag }}">{{message}}</p>
    {% endfor %}
  </div>
  {% endif %}
  {% block section %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

lipila-project/templates/profile_layout.html
{% extends 'admin_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block section %}


<div class="pagetitle">
  
  <section class="section profile">
    <div class="row">
      <div class="col-xl-4">

        <div class="card">
          <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

            {% if request.user.creatorprofile.profile_image %}
            {% if request.user.creatorprofile.profile_image.url %}

            <img src="{{ request.user.creatorprofile.profile_image.url }}" alt="Profile" class="rounded-circle">
            {% endif %}
            {% else %}
            <img src="{% static 'assets/img/avator.jpeg' %}" alt="default Profile image" class="rounded-circle">
            {% endif %}

            {% if request.user.creatorprofile %}
            <h2>{{ user.creatorprofile.patron_title }}</h2>
            <h3>{{user.patronprofile.creator_category }}</h3>
            <div class="social-links mt-2">
              <a href="{{user.creatorprofile.twitter_url}}" class="twitter" target="_blank"><i
                  class="bi bi-twitter"></i></a>
              <a href="{{user.creatorprofile.facebook_url}}" class="facebook" target="_blank"><i
                  class="bi bi-facebook"></i></a>
              <a href="{{user.creatorprofile.instagram_url}}" class="instagram" target="_blank"><i
                  class="bi bi-instagram"></i></a>
              <a href="{{user.creatorprofile.linkedin_url}}" class="linkedin" target="_blank"><i
                  class="bi bi-linkedin"></i></a>
            </div>
            {% else %}
            <h2>{{ user.username }}</h2>
            <h3>Member</h3>
            <h3>{{user.patronprofile.city | upper}}</h3>
            {% endif %}
          </div>
        </div>

      </div>

      <div class="col-xl-8">
        <div class="card">
          <div class="card-body pt-3">
            <ul class="nav nav-tabs nav-tabs-bordered">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'patron:profile' %}">Overview</a>
              </li>
              {% if request.user.creatorprofile %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'patron:update_profile' user=user %}">Edit Patron Info</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'patron:update_personal_info' user=user %}">Edit Personal Info</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'password_change' %}">Change Password</a>
              </li>

            </ul>
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>

</div>
</div>
</section>


{% endblock %}