accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('sign-out', views.custom_logout, name='logout'),
    path('signin/', views.custom_login_view, name="signin"),
    path('sent/', views.activation_sent_view, name="activation_sent"),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),
    
    #Callback urls
    path('tiktok/callback/', views.tiktok_callback, name='tiktok_callback'),
    path('google/callback/', views.google_callback, name='google_callback'),
    path('tiktok_oauth/', views.tiktok_oauth, name='tiktok_oauth'),
]

backend/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # adminstrations urls
    path('admin/', admin.site.urls),

    # api urls
    path('', include('lipila.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('patron/', include(('patron.urls', 'patron'), namespace='patron')),
    path('momo', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('multimedia/', include(('file_manager.urls', 'file_manager'), namespace='file_manager')),
]

lipila/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from patron import views as patron_views
from django.conf.urls import handler404


handler404 = views.custom_404_view


urlpatterns = [
    # message
    path('messages/', views.customer_messages_view, name='customer_messages'),
    path('messages/reply/<int:message_id>/', views.reply_to_message_view, name='reply_to_message'),
    # checkout urls
    path('checkout/<int:id>', views.checkout_subscription, name ="checkout_subscription"),
    path('support/<str:payee>/', views.checkout_momo, name ="checkout_momo"),
    path('checkout/visa/', views.create_purchase, name ="create_purchase"),

    # Luso public urls
    path('', views.index, name='index'),
    path('about/luso', views.about, name='about'),
    path('<str:title>/', views.creator_index, name='creator_index'),
    path('contact/lpa/', views.contact, name='contact'),

    # PatronUser defined authenticated user views
    path('dashboard/me/', patron_views.dashboard, name='dashboard'),
    path('dashboard/staff/', views.staff_users, name='staff_dashboard'),
        
    # lipila difened authenticated user views
    path('approve_withdrawals/lpa/', views.approve_withdrawals, name ='approve_withdrawals'),
    path('processed_withdrawals/lpa/', views.processed_withdrawals, name ='processed_withdrawals'),
    path('faq/ls/', views.pages_faq, name='faq'),
    path('terms-of-use/ls/', views.pages_terms, name='terms'),
    path('privacy-policy/ls', views.pages_privacy, name='privacy'),

    path('history/transfers/', views.transfers_history, name='transfers_history'),
    # Authenticated User's Transaction History endpoints
    path('history/withdrawals/', patron_views.withdrawal_history, name='withdrawals_history'),
    path('subscription/history/paid/', patron_views.payments_history, name='subscriptions_history'),
    
    # Modal-forms urls
    path('money/transfer/', views.money_transfer_view, name ='money_transfer'),
    path('withdrawals/request', views.CreateWithdrawalRequest.as_view(), name ='withdrawals'),
    path('update/<int:pk>', views.TierUpdateView.as_view(), name ='update_tier'),
    path('view/<int:pk>', views.TierReadView.as_view(), name ='view_tier'),
    path('delete/<int:pk>', views.TierDeleteView.as_view(), name ='delete_tier'),

    path('unsubscribe/<int:tier_id>', views.UnsubScribeView.as_view(), name='unsubscribe'),
    path('tiers/ls', views.tiers, name = 'tiers'),

    path('approve/<int:pk>', views.ApproveWithdrawModalView.as_view(), name='approve_withdraw'),
    path('reject/<int:pk>', views.RejectWithdrawModalView.as_view(), name='reject_withdraw'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

patron/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     path('request-payment/', views.PatronPaymentRequestView.as_view(), name='request-payment'),
     # Public URLS
     path('creators/', views.index, name='index'),

     path('creators/list', views.browse_creators, name='creators'),
     path('my-tiers', views.view_tiers, name='tiers'),
     path('join/<int:tier_id>', views.subscribe_view, name='join_tier'),
     path('patron/all/', views.view_patrons_view, name='patrons'),
     path('subscriptions/', views.subscriptions, name='subscriptions'),
     path('subscription/<int:tier_id>', views.subscription_detail, name='subscription_detail'),
     path('withdraw/', views.withdrawal_request, name='withdraw_request'),

     # Profile views
     # cretaor kyc
     path('accounts/profile/kyc/overview', views.kyc, name='kyc'),
     path('accounts/profile/kyc/<int:pk>', views.kyc_review, name='kyc_review'),
     path('accounts/profile/continue/fans', views.continue_has_fan, name="continue_has_fan"),
     path('accounts/profile/', views.profile, name='profile'),
     path('accounts/profile/edit/<str:user>/patron', views.ProfileEdit.as_view(), name='update_profile'),
     path('accounts/profile/edit/<str:user>', views.EditPersonalInfo.as_view(), name='update_personal_info'),
     path('accounts/profile/create/creator', views.create_creator_profile,
          name='create_creator_profile'),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/reusables/_aside_creator.html
{% load static %}

<li class="nav-item">
    <a class="nav-link " href="{% url 'dashboard' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
    </a>
</li>

<li class="nav-item">
    
    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-journal-text"></i><span>Actions </span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="forms-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">
        <li>
            <a href="{% url 'patron:withdraw_request' %}">
                <i class="bi bi-circle"></i><span>Cashout</span>
            </a>
        </li>
        <li>
            <a href="{% url 'patron:tiers' %}">
                <i class="bi bi-circle"></i><span>Tiers</span>
            </a>
        </li>
        <li>
            <a href="{% url 'patron:kyc' %}">
                <i class="bi bi-circle"></i><span>KYC</span>
                {% if request.user.creatorprofile.is_verified %}
                <span class="badge badge-success">Verified</span>
                {% endif %}
            </a>
        </li>
    </ul>
</li>
<li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-layout-text-window-reverse"></i><span>Log</span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="tables-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">
        <ul id="forms-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">

        </ul>
        <li>
            <a href="{% url 'patron:patrons' %}">
                <i class="bi bi-circle"></i><span>Patrons</span>
            </a>
        </li>
        <li>
            <a href="{% url 'withdrawals_history' %}">
                <i class="bi bi-circle"></i><span>Payouts</span>
            </a>
        </li>
        <li>
            <a href="{% url 'subscriptions_history' %}">
                <i class="bi bi-circle"></i><span>Receipts</span>
            </a>
        </li>
    </ul>
</li>

templates/reusables/_aside_regular.html
{% load static %}

<li class="nav-item">
    <a class="nav-link " href="{% url 'dashboard' %}">
        <i class="bi bi-grid"></i>
        <span>Home</span>
    </a>
</li><!-- End Dashboard Nav -->

<li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-journal-text"></i><span>Actions </span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="forms-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">
        <li>
            <a href="{% url 'patron:create_creator_profile' %}">
                <i class="bi bi-circle"></i><span>Start Earning</span>
            </a>
        </li>
        <li>
            {% with target_fragment='#find-creator' %}
        <li>
            <a href="{% url 'patron:creators' %}?fragment={{ target_fragment }}">
                <i class="bi bi-circle"></i><span>Browse creators</span>
            </a>
        </li>
        {% endwith %}
    </ul>
</li>

<li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-layout-text-window-reverse"></i><span>Log</span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="tables-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">
        <li>
            <a href="{% url 'subscriptions_history' %}">
                <i class="bi bi-circle"></i><span>Payments</span>
            </a>
        </li>
    </ul>
</li>

templates/reusables/_aside_staff.html
{% load static %}
<li class="nav-item">
    <a class="nav-link " href="{% url 'dashboard' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-journal-text"></i><span>Actions </span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="forms-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">
        <li>
            <a href="{% url 'money_transfer' %}">
                <i class="bi bi-circle"></i><span>Transfer</span>
            </a>
        </li>
        
    </ul>
</li><!-- End Forms Nav -->
<li class="nav-item">
    <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-layout-text-window-reverse"></i><span>Log</span><i class="bi bi-chevron-down ms-auto"></i>
    </a>
    <ul id="tables-nav" class="nav-content collapsed " data-bs-parent="#sidebar-nav">
        <li>
            <a href="{% url 'processed_withdrawals' %}">
                <i class="bi bi-circle"></i><span>Withdrawals Processed</span>
            </a>
        </li>
    </ul>
</li>

templates/reusables/_checkout.html
<div class="donation-container">
    <h2>Choose an amount (ZMW)</h2>
    <div class="amount-options">
        <button class="amount-btn">K15</button>
        <button class="amount-btn selected">25</button>
        <button class="amount-btn">K50</button>
        <div class="custom-amount">
            <label for="custom">Own amount: K</label>
            <input type="number" id="custom" class="custom-input">
        </div>
    </div>
    <div class="options">
        <label>
            <input type="checkbox">
            I'll generously add K2.50 to cover fees.
        </label>
    </div>
</div>

templates/reusables/_creators.html
{% load static %}
<div class="section-title" data-aos="fade-up">
    <h3>Browse Creators</h3>
</div><!-- End Section Title -->
{% include 'reusables/_filter_creators.html' %}
<div class="creator-container">
    {% for creator in creators %}
    <div class="creator-profile column {{creator.creator_category}}">
        <div class="">
            <div class="user-image">
                {% if creator.profile_image %}
                {% if creator.profile_image.url %}
                <img src="{{creator.profile_image.url}}" alt="profile image" class="img-fluid">
                {% endif %}
                {% else %}
                <img src="{% static 'assets/img/avator.jpeg' %}" alt="profile image" class="img-fluid">
                {% endif %}
            </div>
            <div class="">
                <p>{{creator.creator_category}}</p>
                <h3 class="name">{{creator.patron_title}}</h3>
                <p class="username">@{{creator.user}}</p>
                <div class="links">
                    <a class="facebook c-a" href="{{creator.facebook_url}}" target="_blank"
                        title="{{creator.user}}_facebook">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a class="linkedin c-a" href="{{creator.linkedin_url}}" title="{{creator.user}}_linkedin"
                        target="_blank">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a class="insta c-a" href="{{creator.instagram_url}}" target="_blank"
                        title="{{creator.user}}_instagram">
                        <i class="fab fa-instagram-square"></i>
                    </a>
                </div>
                <p class="details">
                    {% if creator.about %}
                    {{creator.about}}
                    {% endif %}
                </p>
                {% if request.user.is_staff %}
                {% if not creator.is_verified %}
                <a href="{% url 'patron:kyc_review' creator.pk %}" class="btn btn-sm">Review</a>
                {% else %}
                <span class="badge badge-success">Verified</span>
                <a href="{% url 'patron:kyc_review' creator.pk %}" class="btn btn-sm">Review</a>
                {% endif %}
                {% endif%}
                <a class="btn-get-started" href="{% url 'creator_index' creator.user.creatorprofile.patron_title %}">
                    View
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- This is link of adding small images
		which are used in the link section -->
<script src="https://kit.fontawesome.com/704ff50790.js" crossorigin="anonymous">
</script>

templates/reusables/_filter_creators.html
<div id="myBtnContainer" class="breadcrumb">
    <button class="filter-btn filter-active" onclick="filterSelection('all')"> Show all</button>
    <button class="filter-btn" onclick="filterSelection('filmmaker')"> Filmmakers & Content Creators</button>
    <button class="filter-btn" onclick="filterSelection('educator')"> Educators & Mentors</button>
    <button class="filter-btn" onclick="filterSelection('musician')"> Musicians</button>
    <button class="filter-btn" onclick="filterSelection('artist')"> Visual Artists </button>
    <button class="filter-btn" onclick="filterSelection('writer')"> Writers & Poets </button>
    <button class="filter-btn" onclick="filterSelection('craftmaker')"> Craft Makers </button>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        filterSelection("all");
    })
    function filterSelection(c) {
        var x, i;
        x = document.getElementsByClassName("column");
        if (c == "all") c = "";
        for (i = 0; i < x.length; i++) {
            w3RemoveClass(x[i], "show");
            if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
        }
    }

    function w3AddClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            if (arr1.indexOf(arr2[i]) == -1) { element.className += " " + arr2[i]; }
        }
    }

    function w3RemoveClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            while (arr1.indexOf(arr2[i]) > -1) {
                arr1.splice(arr1.indexOf(arr2[i]), 1);
            }
        }
        element.className = arr1.join(" ");
    }


    // Add active class to the current button (highlight it)
    var btnContainer = document.getElementById("myBtnContainer");
    var btns = btnContainer.getElementsByClassName("btn");
    for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function () {
            var current = document.getElementsByClassName("active");
            current[0].className = current[0].className.replace(" active", "");
            this.className += " active";
        });
    }
    // End filter
</script>

templates/reusables/_footer.html
 <!-- ======= Footer ======= -->
 <footer id="footer" class="footer">
    <div class="container copyright text-center mt-4">
        <p>&copy; <span>Copyright</span> <strong class="px-1">Lipila Technologies Ltd</strong> <span>All Rights
                Reserved</span></p>
        <div class="credits">
            Designed by <a href="#">Lipila Technologies Limited</a>
        </div>
    </div>
</footer><!-- End Footer -->

templates/reusables/_get_started_btn.html
<a href="{% url 'accounts:signup' %}" class="btn btn-get-started">Get Started</a>

templates/reusables/_get_started_free_btn.html
<a href="{% url 'accounts:signup' %}" class="btn btn-get-started">Get Started FREE with Luso</a>

templates/reusables/_header_backend.html
{% load static %}

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'assets/img/luso/logo.png' %}" width="30" height="30" class="d-inline-block align-top"
                style="border-radius: 25%;"
                alt="">
            Luso
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item dropdown pe-3">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle nav-profile align-items-center " href="#"
                    id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.usersocialauth.avatar_url %}
                    <img src="{{request.user.usersocialauth.avatar_url}}" alt="Profile" class="rounded-circle">
                    {% else %}
                    <img src="{% static 'assets/img/avator.jpeg' %}" alt="profile" class="rounded-circle">
                    {% endif %}
                    {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <h6 class="dropdown-header">@{{ user.username }}</h6>
                    <hr class="dropdown-divider">
                    <a class="dropdown-item" href="{% url 'patron:profile' %}"><i class="bi bi-person"></i>Profile</a>
                    <a class="dropdown-item" href="{% url 'patron:profile' %}"><i class="bi bi-gear"></i>Settings</a>
                    <a class="dropdown-item" href="{% url 'faq' %}"><i class="bi bi-question-circle"></i>Need Help?</a>
                    <a class="dropdown-item">
                        <i class="bi bi-logout"></i>
                        <form method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                            <span><button type="submit" class="btn btn-dark">Logout</button></span>
                        </form>
                    </a>
                </div>
            </li>
        </ul>
    </nav><!-- End Icons Navigation -->
</header><!-- End Header -->

templates/reusables/_header_frontend.html
{% load static %}
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'assets/img/luso/logo.png' %}" width="30" height="30" class="d-inline-block align-top"
            style="border-radius: 25%;" alt="">
        Luso
    </a>
    <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav nav-tabs">

            {% if request.user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link active" href="{% url 'dashboard' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% endif %}

            <!-- End conditional links -->

            <!-- General links -->
            {% with target_fragment='#creators-info' %}
            <li class="nav-item dropdown">
                <div class="dropdown dropright">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">I'm a Creator</a>
                    <div id="dropdown-menu" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'patron:index' %}#visual-artists">Visual Creator</a>
                        <a class="dropdown-item" href="{% url 'patron:index' %}#musicians">Musician-Actor</a>
                        <a class="dropdown-item" href="{% url 'patron:index' %}#photographers">Creative Educator-Mentor</a>
                        <a class="dropdown-item" href="{% url 'patron:index' %}#writers-poets">Writer-Storyteller</a>
                        <a class="dropdown-item" href="{% url 'patron:index' %}#craft-makers-designers">CraftMaker-Designer</a>
                        <a class="dropdown-item" href="{% url 'patron:index' %}#filmmakers-videographers">Filmmaker-Content Creator</a>
                    </div>
                </div>
            </li>
            {% endwith %}
            {% with target_fragment='#find-creator' %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'patron:creators' %}?fragment={{ target_fragment }}">Browse
                    Creators</a>
            </li>
            {% endwith %}
            <li class="nav-item">
                <a class="nav-link" href="/#contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <form class="nav-link" method="post" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <button type="submit" id="btn-getstarted" class="btn-getstarted">Logout</button>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signin' %}">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/reusables/_nav_frontend.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light" style="background-color: #1e4a6a;">
    <a href="{% url 'index' %}" class="navbar-brand">
        <span class="navbar-text" style="color: aliceblue;">
            Luso
          </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <!-- COnditional links -->

            <li class="nav-item active">
                <a class="nav-link navbar-text" href="{% url 'index' %}" style="color: antiquewhite;">Home <span class="sr-only">(current)</span></a>
            </li>
            <!-- End conditional links -->

        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="navbar-nav">
            
            <li class="nav-item">
                <form class="nav-link" method="post" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <button type="submit" id="btn-getstarted" class="btn-getstarted">Logout</button>
                </form>
            </li>
            
        </ul>
    </div>
</nav>

templates/reusables/_tier_details.html
{% load static %}
<div class="creator-container">
    <div class="creator-profile">
        <div class="user-image">
            {% if subscription.profile_image %}
            {% if subscription.profile_image.url %}
            <img src="{{subscription.profile_image.url}}" alt="profile image" class="img-fluid">
            {% endif %}
            {% else %}
            <img src="{% static 'assets/img/avator.jpeg' %}" alt="profile image" class="img-fluid">
            {% endif %}
        </div>
        <div class="content">
            <input type="hidden" name="amount" id="amount" value={{subscription.tier.price}}>
            <input type="hidden" name="tier_name" id="tier_name" value={{subscription.tier.name}}>
            <h3 class="name">{{subscription.tier.name}}</h3>
            <p class="username">@{{subscription.tier.creator}}</p>
            <p class="username">K{{subscription.tier.price}}</p>
            <p class="details">
                {{subscription.tier.description}}
            </p>
            <div class="links">
                <a class="facebook c-a" href="{{subscription.tier.facebook_url}}" target="{{subscription.tier.name}}_blank" title="{{subscription.tier.name}}_facebook">
                    <i class="fab fa-facebook"></i>
                </a>
                <a class="linkedin c-a" href="{{subscription.linkedin_url}}" title="{{subscription.tier.name}}_linkedin" target="_blank">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a class="insta c-a" href="{{subscription.instagram_url}}" target="_blank" title="{{subscription.tier.name}}_instagram">
                    <i class="fab fa-instagram-square"></i>
                </a>
            </div>
            <p class="details">
                {{subscription.tier.about}}
            </p>
            
            <div class="row">
                {% if subscription.tier.id %}
                <button id="subscribe-btn" data-url="{% url 'checkout_subscription' subscription.tier.id %}" class="m-btn btn-sm m-btn-primary"
                    type="submit" name="button">Pay</button>

                <button data-url="{% url 'unsubscribe' subscription.tier.id %}" id="unsubscribe-btn" class="m-btn btn-sm btn-danger" type="button"
                    name="button">Unsubscribe</button>
                {% endif %}
                <div class="d-flex justify-content-center">
                    <div class="col-12 mb-3">
                    </div>
                    <div class="col-12 mb-3">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

<!-- This is link of adding small images
		which are used in the link section -->
<script src="https://kit.fontawesome.com/704ff50790.js" crossorigin="anonymous">
</script>

templates/reusables/_tiers_table.html
<table>
  <thead>
    <tr>
      <th class="text-center" scope="col">#</th>
      <th class="text-center" scope="col">Title</th>
      <th class="text-center" scope="col">Description</th>
      <th class="text-center" scope="col">Price</th>
      <th class="text-center" scope="col">Visible to Fans</th>
      <th class="text-center" scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for tier in tiers %}
    <tr>
      <td data-label="#" scope="row">{{ forloop.counter }}</td>
      <td data-label="Name"> {{ tier.name }}</td>
      <td data-label="Description"> {{ tier.description }}</td>
      <td data-label="Price">{{ tier.price }}</td>
      {% if tier.visible_to_fans %}
      <td data-label="Visible to Fans">Yes</td>
      {% else %}
      <td data-label="Visible to Fans">No</td>
      {% endif %}
      <td>
        <!-- Update tier buttons -->
        {% if not tier.is_editable %}
        <button type="button" class="update-tier m-btn btn-sm m-btn-primary"
          data-form-url="{% url 'update_tier' tier.id %}">
          Edit
        </button>
        {% else %}
        <button type="button" class="update-tier m-btn btn-sm m-btn-primary"
          data-form-url="{% url 'update_tier' tier.id %}">
          Edit
        </button>
        {% endif %}
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>